### ISSUE TITLE
Autofill every artist in multiplae artist field.

### ISSUE THREAD

**Issue by VikasRana** [SavageCore/yadg-pth-userscript#1]
Particularly in VA albums/compilations

**Comment by SavageCore** [comment]
Um, what are you asking for here? It does fill in all artists?

**Comment by VikasRana** [comment]
Artists not filled when I select the multiple artists album. I want it to fill in artist using track info please.

http://s27.postimg.org/qfqb7ermr/screenshot_1611.png

I am trying this link : http://www.junodownload.com/products/shapeless-techno-vol-5-paranormal-techno/3320826-02/

Would itbe possible?

**Comment by SavageCore** [comment]
Oh I see, that should work, so it must be a bug. Post an issue at [Slack06/yadg](https://github.com/Slack06/yadg).
