### ISSUE TITLE
[Feature request] Add ability use userscript manager Storage API

### ISSUE THREAD

**Issue by Mehavoid** [SavageCore/yadg-pth-userscript#102]
Refs: https://violentmonkey.github.io/api/gm/#gm_getvalue
https://wiki.greasespot.net/GM.getValue
https://www.tampermonkey.net/documentation.php?version=4.8.41&ext=dhdg&show=dhdg&locale=en#GM_getValue

We may have to separate the user settings for each of the sites, likes this: `{'red': ..., 'ops': ...}`

**Comment by SavageCore** [comment]
What's the value of this over native LocalStorage?

**Comment by SavageCore** [comment]
Closing as no response
