### ISSUE TITLE
Lock artist and title fields when editing existing torrent group?

### ISSUE THREAD

**Issue by SavageCore** [SavageCore/yadg-pth-userscript#13]
Requested by Faunts

> If making a request from an existing torrent group this script will replace any existing artist names and the album title, which might not normally be a problem - except when it comes to classical music. I wish the script could "lock" those fields, like when you add a new format to a torrent group.

**Comment by Iksxsuzil** [comment]
I correctly understand that it is necessary only for `requests.php?action=new&groupid=123456` ?

**Comment by Iksxsuzil** [comment]
Yes, all done. I can create PR?

**Comment by SavageCore** [comment]
Please do, it's great to have some contributions!

**Comment by SavageCore** [comment]
Closed by #15

**Comment by SavageCore** [comment]
Released in [v1.6.0](https://github.com/SavageCore/yadg-pth-userscript/tree/v1.6.0)
