### ISSUE TITLE
Metal Archives fetcher doesn't work

### ISSUE THREAD

**Issue by CypherNL** [SavageCore/yadg-pth-userscript#27]
If i search an album with YADG on Redacted with the Metal Archives plugin. It will search for the desired album but does not fetch the information of the album. Instead it put out this:
> I could not find the release with the given ID. You may want to try again with another one.

This is the same if i put the URL of the album in the YADG input field.

**Script version:** 1.7.0
**Browser:** Firefox Nightly 69.0a1
**Userscript plugin:** Violentmonkey 2.10.5

If you need more info, please let me know.

**Comment by SavageCore** [comment]
Not a script issue, as scrapes fail at [yadg.cc](https://yadg.cc/). Please report backend issues [here](https://gitlab.com/Slack06/yadg).

Thanks!
