### ISSUE TITLE
[Feature request] Support DB9

### ISSUE THREAD

**Issue by awsms** [SavageCore/yadg-pth-userscript#39]

**Comment by SavageCore** [comment]
Again no DB9 account, looking for PR!

**Comment by Mehavoid** [comment]
Do you have a nice email? @SavageCore

**Comment by SavageCore** [comment]
> Do you have a nice email? @SavageCore

https://savagecore.uk/privatebin/?d7ac60a0a495ffdd#du3sC1mya1ZVugzsPzEGi8p4jMVCfxm2MwEeq0QVH9Y= (burns after reading)

**Comment by Mehavoid** [comment]
Done :) @SavageCore

**Comment by wietvergiet** [comment]
Any news on this?

**Comment by SavageCore** [comment]
Implemented with #115, forgot to post!

Working on support for the base tag dropdown box to improve db9.
